org: aschey
app: nfl-misery-index
service: nfl-misery-index

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  get_weeks:
    handler: handler.get_weeks
    warmup: true
    events:
      - http:
          path: /weeks
          method: get
          cors: true
  get_years:
    handler: handler.get_years
    warmup: true
    events:
      - http:
          path: /years
          method: get
          cors: true
plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
