org: aschey
app: nfl-misery-index
service: nfl-misery-index

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    shouldStartNameWithService: true
  environment:
    API_GATEWAY_BASE_PATH: ${self:custom.customDomain.basePath}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  app:
    handler: wsgi_handler.handler
    warmup:
      default:
        enabled: prod
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    dev: dev-api.aschey.tech
    prod: api.aschey.tech
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  warmup:
    default:
      enabled: true
      prewarm: true
      concurrency: 1
      events:
        - schedule: rate(4 minutes)
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'nfl'
    createRoute53Record: false
    certificateName: '*.aschey.tech'
    stage: '${self:custom.stage}'
plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
  - serverless-wsgi
  - serverless-domain-manager
